### ISSUE TITLE
Ping tool does not work on windows

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/atef#129]
## Expected Behavior

I'm not sure how much we care, but I thought this should work

## Current Behavior

```
Traceback (most recent call last):
  File "C:\Users\zlentz\Documents\VSCode\atef\atef\tools.py", line 317, in _ping
    ping_by_host[host] = await self.ping(host)
  File "C:\Users\zlentz\Documents\VSCode\atef\atef\tools.py", line 288, in ping
    proc = await asyncio.create_subprocess_exec(
  File "C:\Users\zlentz\Miniconda3\envs\dev\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\zlentz\Miniconda3\envs\dev\lib\asyncio\base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\zlentz\Miniconda3\envs\dev\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
```

## Possible Solution

Ignore it and hope it goes away

## Steps to Reproduce (for bugs)

1. run on windows

## Context

Annoying test suite failure while trying to test other things locally

## Your Environment

Python 3.9.13

**Comment by ZLLentz** [comment]
This shows up in the result summary as "failed because host unreachable", which may a more pertinent problem to address- should probably show as an internal error.

**Comment by klauer** [comment]
Should we switch to the proactor event loop on Windows? https://docs.python.org/3/library/asyncio-platforms.html#windows (note the limitations of the selector one)

I seem to recall caproto automatically chose this event loop type on Windows, so I find it interesting that yours isn't.
Perhaps we also need a Windows CI job here...

**Comment by ZLLentz** [comment]
It looks like it's picking `WindowsSelectorEventLoop` during the test suite execution.
It picks `WindowsProactorEventLoop` when I invoke `asyncio` directly in an ipython session...

**Comment by ZLLentz** [comment]
atef does the correct thing when run outside of the test suite with the config used in this test suite

renaming this issue appropriately, I'll look at least a little bit into why the wrong loop is selected in pytest only

**Comment by ZLLentz** [comment]
Tracked down to `distributed` changing the windows event loop policy and remaking the event loop on import.

Suggested fix is to make our own properly-configured event loop at the start of the execution of the test suite and also at the start of the execution of `atef check`
